NAME = philo

CC = CC
CFLAGS = -Wall -Wextra -Werror
INCLUDES = -Iincludes

SRC_DIR = src
SRC = $(SRC_DIR)/main.c
OBJ = $(SRC:.c=.o)

.PHONY: all clean fclean re

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)

%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all